version: "3.9"

services:
  db:
    image: postgres:14.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=finance_config
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  django:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    container_name: django
    command: ./docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/finance_config
      - CELERY_BROKER_URL=redis://redis:6379/1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    restart: on-failure

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  celery:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    container_name: worker
    command: ./docker/celery_entrypoint.sh
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/finance_config
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    restart: on-failure

  beats:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    container_name: beats
    command: ./docker/beats_entrypoint.sh
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/finance_config
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
      - django
    restart: on-failure
